### ISSUE TITLE
Support for asynchronously reading/writing stdio

### ISSUE THREAD

**Issue by kryptan** [alexcrichton/tokio-process#10]
I may be misunderstanding something, but `ChildStdin`, `ChildStdout` and `ChildStderr` only implement `std::io::Read`/`Write` which are for synchronous io. How can I asynchronously read/write to them?

Is this simply not yet implemented or is there some way to do it?

**Comment by alexcrichton** [comment]
Oh the `Read` and `Write` implementations for all these types are actually nonblocking, as is evidenced from the [documentation](https://github.com/alexcrichton/tokio-process/blob/9738947a198f8f970f3ea2a1b7940fdd3bb85c02/src/lib.rs#L398-L400). In that sense this is already done!
