### ISSUE TITLE
Investigate using job objects and IOCP on Windows

### ISSUE THREAD

**Issue by luser** [alexcrichton/tokio-process#11]
While reading the MSDN docs on job objects for something, I came across this page:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms684141(v=vs.85).aspx

If you create a job object, you can associate an IOCP with it. If you then create processes in that job (generally using [`AssignProcessToJobObject`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681949(v=vs.85).aspx) on a process that has been created with the `CREATE_SUSPENDED` flag) you will get process event messages on the IOCP, including `JOB_OBJECT_MSG_EXIT_PROCESS`.

**Comment by alexcrichton** [comment]
I was actually pretty excited originally to use job objects as they seemed like a perfect tool, but [this documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684161(v=vs.85).aspx) ended up having a few clauses that dissuaded me:

> Note that, with the exception of limits set with the JobObjectNotificationLimitInformation information class, delivery of messages to the completion port is not guaranteed; failure of a message to arrive does not necessarily mean that the event did not occur.

Do you know if there's a way to work around that though? Perhaps whenever any event happens we should check *all* events like with Unix?

**Comment by luser** [comment]
That warning is infuriatingly vague. I can't find any documentation anywhere that clarifies it! [Raymond Chen suggests](https://blogs.msdn.microsoft.com/oldnewthing/20130405-00/?p=4743) using the IOCP notification `JOB_OBJECT_MSG_ACTIVE_PROCESS_ZERO` to wait for a process tree to exit, so that would suggest that *that* is reliable, at least. That's not the behavior we need here, though, because if you spawn a process that spawns other processes you don't want to have to wait for the grandchild processes to exit as well. [This other article](https://www.microsoft.com/msj/0399/jobkernelobj/jobkernelobj.aspx) by Jeffrey Richter does mention that "by default, a job object is configured so that when the job's allotted CPU time expires, all the job's processes are terminated automatically and the JOB_OBJECT_MSG_END_OF_JOB_TIME notification does not get posted", but you can change that behavior. It's not clear if that's what the MSDN documentation is warning about.

**Comment by alexcrichton** [comment]
So actually... If we could manage to ensure that a child process is the only one (and will only ever be the one) inside of a job object then I think we could use that message, right?

I wonder if we could use `JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK` for that? From reading the documentation I can't quite tell if that means that *all* child processes are not members or if only those that specify `CREATE_BREAKAWAY_FROM_JOB` are not members.

**Comment by luser** [comment]
[Per MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684161(v=vs.85).aspx#managing_processes_in_jobs):

"If the job has the extended limit JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK, then child processes of any parent process associated with the job are not associated with the job. It is not necessary for parent processes to be created with the CREATE_BREAKAWAY_FROM_JOB flag."

**Comment by alexcrichton** [comment]
Well in that case sounds perfect! I'll investigate.

**Comment by alexcrichton** [comment]
Job objects have their own special way of being associated with completion ports (yay special flowers!) so mio will have to expose the actual handle to the completion port somehow. I'll work on implementing that in mio.

**Comment by alexcrichton** [comment]
Blech it also gives no control over an `OVERLAPPED` pointer, so gonna have to rethink a lot in mio for this one...

**Comment by alexcrichton** [comment]
So for me I'm not sure I've got a great way to solve this at the mio layer. It's easy enough to expose the underlying IOCP object, but only having a token to dispatch on is a real bummer. On Windows mio assumes all IOCP events come back with an OVERLAPPED pointer that has a function pointer right behind it, and that's the event's dispatch. With just a token we'd need to have some sort of token-based dispatch ahead of that to treat them specially (somehow) but I'm not sure how to do that efficiently...

I'll open an issue on the mio repo so we can track there though.

**Comment by alexcrichton** [comment]
https://github.com/carllerche/mio/issues/526

**Comment by ipetkov** [comment]
Moving this to tokio-rs/tokio#1337
