### ISSUE TITLE
Spawning a child process and reading its stdout/stderr in a "streaming way"

### ISSUE THREAD

**Issue by ihrwein** [alexcrichton/tokio-process#12]
Hi,

First of all, thanks for this library.

I started to write a service supervisor which can start one subprocess and read the child's stdout and stderr ouputs in a streaming way. For example, I'd like to redirect them to a TCP connection or a file. Is there any way to spawn a child and get handles for both of stdout and stderr? `Child`'s `stdout()` and `stderr()` methods returns mutable references, so they cannot be called at the same time. Why don't you use `self.stderr.take()`?

**Comment by alexcrichton** [comment]
Oh you should be able to `take()` them, but does that not work for you? With the raw I/O handles you should be able to implement w/e logic you need locally in theory at least.

**Comment by ihrwein** [comment]
It works perfectly, thanks. I knew about take(), but I didn't realize I could move out the handles from the references :)
