### ISSUE TITLE
Request for a new release

### ISSUE THREAD

**Issue by ipetkov** [alexcrichton/tokio-process#21]
Hi @alexcrichton, thanks for maintaining this crate!

Is it possible to release a new version sometime in the near future? Hoping to release a crate in the next few weeks but it relies on the `status_async2` changes introduced in #20, which haven't made it into any particular release AFAIK.

Thanks!

**Comment by alexcrichton** [comment]
Certainly! Out of curiosity, would you like to have collaborator + publish rights for this crate as well? You've done some awesome work to help it along!

**Comment by ipetkov** [comment]
@alexcrichton sure, that would be great!
