### ISSUE TITLE
`tokio-process` can't coexist with `tokio`

### ISSUE THREAD

**Issue by Twey** [alexcrichton/tokio-process#27]
`tokio-core` is now deprecated, and the new `tokio` crate has a completely different model for execution.  Notably, there is AFAICT no way to get a `tokio_core::reactor::Handle` or anything similar from `tokio`, which makes many of `tokio-process`'s functions uncallable.

**Comment by alexcrichton** [comment]
Thanks for the report! Once futures 0.2 is published I plan on updating.

**Comment by ipetkov** [comment]
@alexcrichton on an unrelated note, is the plan to release `0.3` once futures 0.2 is out?

**Comment by alexcrichton** [comment]
@ipetkov oh isn't this lib currently at 0.1?, making the futures 0.2 compatible release 0.2?

**Comment by ipetkov** [comment]
Unfortunately we've got a [published, but yanked, 0.2 version](https://crates.io/crates/tokio-process/0.2.0). Releasing a new 0.2.x version will have breaking changes relative to 0.2.0 and will probably cause more problems for anyone that happens to be on 0.2.0.

I figured jumping directly to 0.3 will just bypass any of these headaches and start over!

**Comment by alexcrichton** [comment]
Oh I was gonna publish 0.2.1, while technically breaking I can't imagine anyone's actually relying on 0.2.0

**Comment by ipetkov** [comment]
Fair enough, will trust your judgement here, thanks!

**Comment by tarcieri** [comment]
What's the story here now that futures 0.2 is out?

**Comment by ipetkov** [comment]
@tarcieri I've created a milestone for tracking changes for a 0.2.x release

cc @alexcrichton

**Comment by alexcrichton** [comment]
Thanks @ipetkov! I wonder, does Tokio support futures 0.2 yet?

**Comment by Twey** [comment]
Yes, with the `unstable-futures` feature.

**Comment by ipetkov** [comment]
FWIW, according to tokio-rs/tokio#312 the "[recommendation](https://www.reddit.com/r/rust/comments/8ac85w/futures_02_is_here/dwxkhvl/?st=jfu4ws1v&sh=c3363e5e) from the futures team is to not update libraries fully to 0.2", given that futures 0.3 is on the horizon.

**Comment by Twey** [comment]
Yes, I believe that's true. I must have just missed that on my first time through — I guess the port is easier than I anticipated then.

**Comment by tarcieri** [comment]
It looks like #29 (`tokio-core` => `tokio`) and #30 (`futures` 0.2 upgrade) cover both of these problems as separate issues. Perhaps it's worth closing this issue and moving discussion there?

**Comment by Twey** [comment]
Fine by me.
