### ISSUE TITLE
Depend on `tokio` runtime instead of `tokio-core`

### ISSUE THREAD

**Issue by ipetkov** [alexcrichton/tokio-process#29]
Since `tokio-core` now [supports](https://docs.rs/tokio-core/0.1.16/tokio_core/reactor/struct.Handle.html#method.new_tokio_handle) converting `tokio_core::Handle`s to `tokio::Handle`s, we should depend on the `tokio` runtime which allows downstream crates to use either system

**Comment by ipetkov** [comment]
Note: `tokio-signal` will need to be migrated to using the `tokio` runtime first

**Comment by tarcieri** [comment]
FYI, relevant `tokio-signal` issue: https://github.com/alexcrichton/tokio-signal/issues/22

**Comment by tarcieri** [comment]
Is anyone interested in working on this? If not, I could try working on a PR.

The `tokio-signal` stuff seems like a definite blocker though, and I'm not sure the path forward there is clear.

**Comment by alexcrichton** [comment]
I don't personally have enough time right now to take care of this, but I can help take a look at a PR!

**Comment by euclio** [comment]
The `tokio-signal` 0.2 release contains support for the `tokio` runtime.

**Comment by tarcieri** [comment]
@euclio fantastic!

If I have some spare time I'll take a look at this

**Comment by jjl** [comment]
`tokio_io::IoFuture` doesn't exist in `tokio::io`, but it's used in several places.

**Comment by euclio** [comment]
`IoFuture<T>` is just a type alias for `Box<Future<Item = T, Error = io::Error> + Send>`.

**Comment by ipetkov** [comment]
Found some spare time and started working on this. Will try to wrap up an initial PR for this sometime tomorrow!

**Comment by ipetkov** [comment]
PR opened: #37

**Comment by ipetkov** [comment]
Changes have been merged into the `0.2.x` branch, so going to close this.

Anyone who'd like to give the changes a spin is welcome to do so! Unless any issues are brought up, I'll publish a `0.2.1` version later this week
