### ISSUE TITLE
Consider killing child when `Child` future dropped

### ISSUE THREAD

**Issue by ipetkov** [alexcrichton/tokio-process#3]
The current `std::Child` implementation (which powers the `Child` future) [does not implement `Drop`](https://doc.rust-lang.org/std/process/struct.Child.html#note), so spawned children will continue to run unless they are explicitly killed.

I wonder if maintaining the same behavior within this crate is misleading with respect to the philosophies of futures: 
* dropping a regular future frees up resources and "cancels" the work being done
* a caller must explicitly "forget" a future to keep it running in the background

(Granted child processes already diverge from the philosophy a bit since the child will run regardless if the parent polls the `Child` future, but this gap naturally makes sense in my head)

I propose that the `Child` future implement `Drop` which attempts to `kill()` the underlying child on a best effort basis. I'd be happy to open a PR to implement this if it makes sense to do!

**Comment by alexcrichton** [comment]
Yeah I feel like "futures cancel on drop" is trumps "libstd child doesn't cancel on drop". In that sense I agree we should reverse what libstd is doing with with this crate and cancel on drop by default. I'll add this in with a `forget` method as well to let children run in the background.
