### ISSUE TITLE
Forgotten child processes cannot be reaped

### ISSUE THREAD

**Issue by ipetkov** [alexcrichton/tokio-process#34]
* Similar to #32, we never reap any children which have had `forget` invoked.
* A possible solution is to register a cleanup future with the reactor whenever `forget` is invoked, such that the child is reaped when it exits

**Comment by alexcrichton** [comment]
Hm an excellent point! I'm not sure we'd want to spawn anything though as that could run into long-lived leaks (which this may be intended to avoid). I wonder though if the this should perhaps simply be removed? We could perhaps add an `into_inner` method to return a `Child` which could in theory take over from there?

**Comment by ipetkov** [comment]
Unfortunately, the `std::Child` doesn't offer any clean up either, so unwrapping it will still leak un-reaped children (albeit it would become the caller's problem at that point):

```
/// There is no implementation of `Drop` for child processes,
/// so if you do not ensure the `Child` has exited then it will continue to
/// run, even after the `Child` handle to the child process has gone out of
/// scope.
```

> I'm not sure we'd want to spawn anything though as that could run into long-lived leaks


Could you elaborate on what you mean by long-lived leaks? I could see this being a problem if the event loop isn't actually turning but I'm not sure if that's a common situation.

**Comment by alexcrichton** [comment]
Oh right yeah but it's sort of a clearer way of placing that burden onto the caller. We could very sternly document the warning of leaking pids, and having a `Child` in hand would allow external callers to manage it as required (which may be to just call `drop` or to schedule a future later)

**Comment by ipetkov** [comment]
I was thinking about modifying `forget` (or its equivalent) to just return a future which will ensure the cleanup is done, and require the caller to spawn it in the event loop if needed, but that's not much different than `handle.spawn(child.map(|_| ()).map_err(|_| ())`, so we might as well just recommend that approach.

With that said, I'm fine with just deprecating `forget` and adding more stern documentation/`must_use` markers on `Child` for avoiding OS resource leaks. The proposal for adding `into_inner` doesn't seem required here, but definitely something that can be easily added if/when needed in the future. Thoughts?

**Comment by alexcrichton** [comment]
I think though that this is something we'd want to enable somehow in the sense that despite it being bad in some circumstances it's still good to execute in others. I'd prefer to enable drop-without-kill somehow for those still using it, although I don't think it has to be precisely through the `forget` interface as-is today

**Comment by ipetkov** [comment]
Okay, will open a PR later just for updating the docs.
