### ISSUE TITLE
Does SIGKILL always result in *immediate* termination?

### ISSUE THREAD

**Issue by vorner** [alexcrichton/tokio-process#51]
Looking an the code here: https://github.com/alexcrichton/tokio-process/blob/master/src/unix.rs#L90, the unix kill function claims that the termination is immediate. This is also used in the destructor of the future on the upper level.

However, I don't think this is 100% accurate. I've noticed that:
* If the process has a lot of stuff in swap, the kernel first seems to clean the swap and then make the process really dead.
* If the process gets stuck inside a syscall (eg. waiting on IO on NFS mount without timeout that got disconnected, kernel bug, etc), it doesn't exit until it leaves the syscall, and you can keep sending it `kill -9` like crazy and the process just doesn't go away.

I guess these situations are a bit rare, but still, should this make the library synchronously wait in a destructor? But I don't have a specific solution in mind ☹.

**Comment by ipetkov** [comment]
Hey @vorner, thanks for the report, very interesting finding!

The original motivation behind synchronously waiting in the destructor on the killed child was to avoid leaking zombie processes. The stdlib doesn't implement destructor cleanup for spawned processes, probably to avoid these headaches to begin with. However, given that the futures world treats drops as cancellations (and rust's RAII patterns) I think we should strive to do our best to avoid resource leaks!

One potential solution I can think of is if we run a destructor which requires reaping the child, we could fire the kill signal and enqueue a future on the default executor to reap the child when (if?) it finally exits. The downside to this is we can't guarantee the drop will happen on-task and that a default executor will exist at that time. As a last resort we could do a best effort here and emit a warning/error log message stating we're leaking resources and hope the consumer notices if it becomes a problem.

Alternatively we could adopt a policy of panicking if a process handle is dropped without being reaped (either as a debug assertion only, or a regular panic), unless the caller has marked the child as "safe to leak". This seems a bit heavy handed, and it still doesn't solve the future cancellation story...

These solutions may require waiting until we release a breaking change as I'm not sure how many consumers explicitly depend on the existing semantics, but I'm open to explore any ideas anynone might have!

**Comment by vorner** [comment]
> Alternatively we could adopt a policy of panicking if a process handle is dropped without being reaped (either as a debug assertion only, or a regular panic), unless the caller has marked the child as "safe to leak". This seems a bit heavy handed, and it still doesn't solve the future cancellation story...

I would like to avoid that. I think such policy would make it really hard if not impossible to shut down an application without triggering panics on the way.

In general, the enqueueing of the future sounds like a good idea to me, with some possible improvements. Maybe few calls to `try_wait` with really short time outs in between to catch the more common case of the child terminating right away. Or just having a global list orphaned children to wait on from any wait/call of the signal handler or something in that direction could work as some kind of GC-ish solution?

**Comment by ipetkov** [comment]
The global list of orphaned children sounds like a plausible idea to me!

I'd imagine we'd only poll the "GC queue" whenever we'd normally `try_wait` on a child (i.e. when we know we've gotten a signal), and since orphaning should hopefully be rare, the performance penalty would get amortized to a few atomic ops.

I'll try to prototype something when I get the chance, but happy to review any other PR attempts as well!

**Comment by partim** [comment]
To provide a data point, I have seen hanging `Child` futures in the wild that could be explained by this issue.

[Routinator](https://github.com/nlnetlabs/routinator) needs to spawn `rsync` processes to collect the data it is processing. On one MacOS machine, one of `rsync` process would hang eventually, leading to Routinator’s update routine hanging, too. I added a timeout via a tokio-timer around the future, but that didn’t seem to resolve the issue. This could indeed be explained by the child process not reacting to the SIGKILL. (The issue resolved itself when disabling IPv6 for rsync, so some kernel quirk seems likely.) There has been a similar report on a Linux machine, but I have no detailed data from that occurrence other than ‘it was behind’ as that, unfortunately, was a production setup.

**Comment by ipetkov** [comment]
Okay here's a status update on this issue after merging in #55:

* `kill` no longer reaps the child as it shouldn't be its responsibility
	- This does mean that dropping a `Child` will kill, but leak it in a zombie state
* The internal "is reaped" flag has been optimized out by leaning on the std version which essentially does this already. This avoids the deadlocks described in #57.

Next steps:

* Implement some kind of global queue to hold any orphaned zombie processes so that we can try reaping them at a later time. Roughly:
	- When a `Child` is dropped, it will attempt to push itself on the queue
	- Whenever another running `Child` tries to poll its respective proccess (i.e. it knows a signal has arrived) it can also attempt to drive the queue
	- Driving the queue entails one of two scenarios:
		* Attempt to `tokio::spawn` a zombie reaper which will register its own signal handler and attempt to reap all zombie processes in the queue. That way any non-orphaned children don't get slowed down by doing extra polls
			- If this future get's dropped, it can push the zombies back onto the queue. The tricky bit will be figuring out if we need some kind of sanity check to avoid infinite loops (e.g. some *really* evil process that refuses to die for some reason shouldn't throw the application for a loop)
		* If the spawn fails for any reason then the caller can attempt to poll the contents of the queue
			- We do need to be careful here as well because we could get some performance issues: imagine that an application has N spawned children and M zombies in the queue. When a signal comes in, all N proceses will keep trying to reap the M zombies in the queue
			- However, if this sort of zombification is rare, this won't really be much of an issue

**Comment by ipetkov** [comment]
I've implemented a slightly simpler, but similar, approach as mentioned in my last comment in #58.

@vorner and @partim could you try to do a test and see if the issues have gone away?
Planning to cut a new release sometime next week with the fix, but it would be good to do an extra sanity check if things are working as expected!

**Comment by vorner** [comment]
I haven't actually *reproduced* it in the first place, I've only guessed at the problem from reading source code. But I'll have a look at the new code and try thinking if it *should* go away at least :-)
