### ISSUE TITLE
`spawn_async` et al. should spawn the process lazily.

### ISSUE THREAD

**Issue by cristicbz** [alexcrichton/tokio-process#8]
Right now the subprocess seems to be spawned right away rather than the first time the `Future` is polled. This is a limitation for me since I want to box (with `.boxed`) a whole bunch of `spawn_async` futures without spinning up all the processes at the same time.

I can't use a lazy future and box that, because I'd need to capture a `handle` which isn't `Send`.

Is there some other kind of trick I should be using? Personally I find it surprising that the follwing prints `hello` even though I never call `core.run`:

```rust
extern crate futures;
extern crate tokio_core;
extern crate tokio_process;

use tokio_core::reactor::Core;
use tokio_process::CommandExt;
use std::process::Command;
use std::thread;
use std::time::Duration;

fn main() {
    let core = Core::new().expect("");
    let handle = core.handle();
    let _foo = Command::new("echo").arg("hello").spawn_async(&handle).expect("");
    thread::sleep(Duration::from_secs(1));
}
```

PS: Thanks a lot for this library and `futures-rs`!

**Comment by ipetkov** [comment]
@alexcrichton is there a reason why we have to spawn commands using a `Handle` only? If there is an alternative `spawn_async_remote` API that accepts `Remote` then the spawn could be wrapped as a lazy future since `Remote` is `Clone + Send`

**Comment by alexcrichton** [comment]
Hm an interesting idea! Fundamentally there's no real way to express asynchronous spawning, so I wanted to keep that fact exposed at the API layer if possible. Perhaps something like this could work though?

```rust
let remote = ...;
let cmd = ...;
let future = lazy(|| {
    let (tx, rx) = oneshot::channel();
    remote.spawn(|handle| tx.complete(cmd.spawn(handle))));
    rx
});
```

or something like that?

@ipetkov part of the `spawn` operation needs to register I/O handles on the event loop (e.g. stdio handles) as well as signal handling and such for Unix. That's basically the only reason a `Handle` is required rather than a `Remote` for now.

**Comment by ipetkov** [comment]
@alexcrichton ah, didn't look at the `Remote` docs too closely and missed that `spawn` gives access to a regular `Handle`

**Comment by cristicbz** [comment]
@alexcrichton using a oneshot channel always feels like giving up, but you're right, I didn't think about the fact that ultimately the OS doesn't support async spawning. Thanks for the run-through, I'll close this since it seems like this is just the way this API needs to work (I'm still getting used to what is idiomatic tokio).
